tasks:
  - name: Browser Sync
    init: npm install -g browser-sync && alias startweb='npx browser-sync start -s -w' && clear && npx browser-sync start -s -w
  - name: Dependencies & Database
    init: |
      bundle install
      rails db:setup